// © 2024 Long Ly. All rights reserved. Any unauthorized use, reproduction, or distribution of this trademark is strictly prohibited and may result in legal action.

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/CheatManager.h"
#include "OLSCheatManager.generated.h"

/**
 * 
 */
UCLASS()
class OLS_API UOLSCheatManager : public UCheatManager
{
	GENERATED_BODY()

public:
	
	UFUNCTION(Exec)
	void CheatModifyMaxSpeed(const float speed = 0.f);
	
public:

	UFUNCTION(Exec)
	void ToggleDebugAnim(const bool shouldEnable) const;
};
